### PR TITLE
Fix typo 'recieve'

### PR DESCRIPTION
**Pull request by TheTypoMaster**

### CODE REVIEW

**Comment by sbrl** [comment]
Thanks so much! I must have missed that.

First pull request ever: merged!

**Comment by sbrl** [comment]
Suggestion: If this is a bot, perhaps including some information in the description about the bot would be helpful :)

**Comment by TheTypoMaster** [comment]
Yes, that's a good idea! I tried to do that, but it broke my application, and because I was in a bit of a rush I didn't have time to fix it. I deleted it afterwards and just didn't go back to it, but yes, I've thought about that and I'm going to implement that as soon as I'm done with other core features (like looping through words in a text file, scraping (have to do a thing manually), buy hosting etc etc). Do you have any idea of how the message could potentially be formatted?

**Comment by sbrl** [comment]
I'm probably not the best person for this, but the description of the pull request could perhaps look something like this:

> Hi! I'm a bot that checks GitHub for spelling mistakes, and I found one in your repository. I created this pull request to fix it!

By the way, is the source for your bot on GitHub? This sounds like an awesome idea.

**Comment by TheTypoMaster** [comment]
That's really good. Perhaps we could also add "(looking for the source of the bot? Go here!)" or something to get people more involved with this bot. I can also add "Anything that is wrong with this or perhaps you have a question? Please mail me at x@x.x" (better written though).

The code sadly isn't on GitHub yet but I'll definitely try to add it. I'm kinda of ashamed of the code I've written right now, big security holes and a lot of repetition. I'll probably have someone look at my code (before I publish it) because I haven't worked in Python nor the GitHub Api that much. Here is the words my bot soon is gonna correct though :) (correct word - misspelled word)
https://gist.github.com/TheTypoMaster/d79d8b655158aa6bbc26

**Comment by TheTypoMaster** [comment]
Oh, also, I'm 13 and swedish. Pardon me if I make a spelling mistake or something is wrong. :)

**Comment by TheTypoMaster** [comment]
If you're interested, I think this is gonna be how it looks:

> Hi! I'm a bot that checks GitHub for spelling mistakes, and I found one in your repository. When it should be x, you typed x. I created this pull request to fix it!
> 
> If you think there is anything wrong with this pull request or just have a question, be kind to mail me at thetypomaster@hotmail.com (professional email, huh?). I’ll try to address the problem as soon as I’m aware of it.
> 
> Looking for the source code of this bot? Well, you have to be patient! The bot is under development and I will publish the source code as soon as I’m finished with it.
> 
> With kind regards,
> TheTypoMaster

**Comment by sbrl** [comment]
Yeah. That would definitely be a good idea.

I can't believe that someone hasn't thought of this before. I'm a University student. I also know some python - I might be able to take a took if you want :)

That list is good! By the way, are you going for American English, or British English? I _might_ be able to take a spell checking dictionary and parse it into a list of confident find / replace pairs for you - though you have a good list already!

Yep, that looks awesome for a description.

**Comment by sbrl** [comment]
Update: I've found a [list of common spelling mistakes on wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines). I downloaded it, converted it to your format with [this code](https://gist.github.com/sbrl/459826d8f30ba6a60cae), combined it with your existing list (with a bit of `cat file | sort | uniq -u` magic), and [here's the resulting list](https://gist.github.com/sbrl/83280fdd5ff9f63104b5).

**Comment by sbrl** [comment]
Oh and your English is amazing - I honestly wouldn't have guessed you didn't speak it as your first language.

**Comment by TheTypoMaster** [comment]
Thank you! And that's such a big list!? I'll definitely use this. I want to scrape 5 projects of every word I search for, that's 22.540 projects fixed when it has completed the list. I'm going for both American english and British english by the way. Thank you for helping me out in this way. Oh, and do you have any social network that is better to talk on/or a chat forum? The GitHub comments on a pull request seems a little... weird, haha :)

**Comment by sbrl** [comment]
No problem - I'm glad I could be of help!

Now that I think about it... It does seem rather odd to hold a conversation in a github pull request :P

I've got an email address: sbrl@starbeamrainbowlabs.com. I don't have a forum, but I could set one up on my server, and I have a XMPP/jabber account too, whose address is the same as my email address. If you prefer google chat, I also have starbeamrainbowlabs@gmail.com. Take your pick :D

**Comment by sbrl** [comment]
Oh yeah, if you send me an email I'd find it helpful if you commented here just for the first one - I run my own mail server, so I sometime need to make sure that messages do actually get though :)

**Comment by TheTypoMaster** [comment]
Hello, sorry. I've been busy and haven't been able to respond (lots of school). Yes, I will :) Not sure when, but I will do it!

**Comment by sbrl** [comment]
No problem :) Take as long as you need! I'm pretty busy too.

**Comment by TheTypoMaster** [comment]
I've sent an email!

**Pull request merged**
